### PR TITLE
Hide shadow warning

### PR DESCRIPTION
**Pull request by pgruenbacher**
when ccflags have all warnings enabled, there's lots of warnings regarding entt headers and shadowing. While there's no issue with how the code is setup, it is nice to have the lambda function parameters different from the above scope.

This was caused when compiling godot 3.1 release with entt

I just added _ prefix to the variable name, idk what you preference is.

```
/home/pgruenbacher/Code/cpp/entsim/thirdparty/entt/src/entt/meta/meta.hpp: In lambda function:
/home/pgruenbacher/Code/cpp/entsim/thirdparty/entt/src/entt/meta/meta.hpp:1436:97: warning: declaration of 'curr' shadows a previous local [-Wshadow=local]
         const auto *curr = internal::find_if([key = meta_any{std::forward<Key>(key)}](auto *curr) {
```

### CODE REVIEW

**Comment by pgruenbacher** [comment]
oops i included some bad commits.... ignore ignore!

**Comment by pgruenbacher** [comment]
https://github.com/skypjack/entt/pull/207/commits/6e1f719bfac28b47c5a2868cd29fa40452f54e51 this is the specific commit. I'm too lazy to cherry pick since you'll probably want to rename the changed variables to fit your own preference but I'll leave this open for your reference.

**Comment by skypjack** [comment]
Sure, thanks. I'll merge this on a branch and change the names if needed to fit the naming conventions of the project.  
Your PR is really helpful to spot what to change btw. :+1:

Thanks!!

**Comment by skypjack** [comment]
There were conflicts on this PR and a lot of classes weren't updated to avoid shadowing.  
I picked the part that _works_ (for some definitions of work) and made a separated push on branch `experimental`.  
If it works as expected, I'll merge it upstream and close this. :+1:

**Pull request closed without merging**
