### PR TITLE
Add Dispatcher header to EnTT global include

### PR DESCRIPTION
**Pull request by gale93**
Or is there a reason why it is not included?

### CODE REVIEW

**Comment by gale93** [comment]
Ehm sure, how do you want it to be called ?
Then, the name of pull request or the commit too ? ^^"

**Comment by skypjack** [comment]
Ahahahah... no, no, I mean this:
```
#include "signal/bus.hpp"
#include "signal/delegate.hpp"
#include "signal/dispatcher.hpp"
#include "signal/emitter.hpp"
#include "signal/sigh.hpp"
#include "signal/signal.hpp"
```
Instead of this:
```
#include "signal/bus.hpp"
#include "signal/delegate.hpp"
#include "signal/emitter.hpp"
#include "signal/sigh.hpp"
#include "signal/signal.hpp"
#include "signal/dispatcher.hpp"
```
That's all.

**Comment by gale93** [comment]
Oh, well, shame on me ! x)

**Comment by skypjack** [comment]
Thank you very much.

**Pull request merged**
