### PR TITLE
Update packages with Travis-CI

### PR DESCRIPTION
**Pull request by Kerndog73**
Turning issue #109 into a pull request.

This is difficult to test.

### CODE REVIEW

**Comment by Kerndog73** [comment]
The script definitely works but I don't know of any way to test the whole thing until another tag is created.

**Comment by Kerndog73** [comment]
Can the vcpkg package be updated with a script?

**Comment by skypjack** [comment]
You can remove that part. It looks like [they have their own system](https://github.com/Microsoft/vcpkg/pull/3287) to updated registered packages.  
Is it possible to name script as `.sh` instead of `.bash` and add a `#!/bin/sh` line to the top?

**Comment by Kerndog73** [comment]
I removed the `#!/bin/bash` part because the script will need executable permissions. So you'll have to do `chmod +x script.bash`. I think so

**Comment by skypjack** [comment]
>I don't know of any way to test the whole thing until another tag is created

I like this risky stuff!! Isn't there a way to test it? Really? Otherwise we can create a v2.7.2 tag for this purpose. I don't think users will complain about it.

**Comment by Kerndog73** [comment]
The script is easy to test but you can't really test the Travis part without creating a new tag and pushing to the remote repo.

**Comment by skypjack** [comment]
>I removed the #!/bin/bash part because the script will need executable permissions. So you'll have to do chmod +x script.bash. I think

I didn't get it. What's the problem? We can just set the executable bit once and push the file, then everything should work as expected. Am I wrong? If I remember right, I did something with a project of mine (`uvw`) a lot of time ago.

**Comment by Kerndog73** [comment]
I did some googling. It turns out that git tracks file permissions. Well you learn something everyday! I can't make this change now as I'm on mobile

**Comment by skypjack** [comment]
I'm alone at home with my son (2 years old). I don't think I'l find the time to do that today. :smile: 
I can work on it for sure tomorrow afternoon. If you manage to do it in the meantime, well... that's good.  
Let me know. I'm willing to merge these changes and test them with the next tag.

**Comment by Kerndog73** [comment]
The output from git suggested that the executable bit was set and the change was committed.

**Comment by skypjack** [comment]
I made some small changes (ie `bin/bash` -> `bin/sh` so as to support different shells).  
Everything is made available on branch `issue_110`. You're still the author of the commit, of course.  
If you confirm that the resulting changes are somehow _valid_, I can merge everything on `master` and we'll test it with the next tag.

**Comment by Kerndog73** [comment]
Looks fine to me. Let's see if it works!

**Comment by Kerndog73** [comment]
The build errored! 😬

When `tags: true` is set, there is an implicit `condition: “$TRAVIS_BRANCH” = “master”`. When a tagged commit is pushed, `$TRAVIS_BRANCH` is set to `$TRAVIS_TAG`. This means that the implicit condition fails and we get `Already up to date!` in the build log.

The solution is quite simple.

```yaml
on:
  tags: true
  condition: “$TRAVIS_BRANCH” = “$TRAVIS_TAG”
```

**Comment by skypjack** [comment]
Good point. Thank you. I'm updating `.travis.yml`.

**Pull request merged**
