### PR TITLE
Fix C4003 NOMINMAX bug

### LINKED ISSUE #96: EnTT really work on windows ?
Hey using vcpkg + entt 2.6.1

```cpp
  entity_registry_.each([this](auto entity) {
                this->entity_registry_.destroy(entity);
            });
````

this snippet doesn't compile with the following error
  ecs-test.cpp

c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(567): warning C4003: not enough actual parameters for macro 'min' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(625): warning C4003: not enough actual parameters for macro 'min' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(633): warning C4003: not enough actual parameters for macro 'max' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(756): warning C4003: not enough actual parameters for macro 'min' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(552): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
  c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(901): note: see reference to class template instantiation 'entt::View<Entity,Component...>' being compiled
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(567): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(625): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(633): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]
c:\tools\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(756): error C2589: '(': illegal token on right side of '::' [C:\projects\shiva\build\tests\ecs-test\ecs-test.vcxproj]

### LINKED ISSUE #530: Fixing the NOMINMAX C4003 bug
As discussed [in the FAQ](https://github.com/skypjack/entt/wiki/Frequently-Asked-Questions#warning-c4003-the-min-the-max-and-the-macro) and [in this issue](https://github.com/skypjack/entt/issues/96), trying to use `std::min` or `std::max` while including `<windows.h>` throws a C4003 error (with `permissive-` enabled.) There is a very simple work around: surround the `std::min` and `std::max` function names with parenthesis.

```
int a = 0;
int b = 1;
a = (std::min)(a, b);
```

The bug is related to the "most vexing parse" problem. Forcing the function name to be evaluated with parenthesis removes the `min` and `max` names from consideration as a macro replacement.

I looked through the single-header implementation of EnTT and there are only a handful of places where `std::min` and `std::max` are used. It would be trivial to add the appropriate changes in less than 5 minutes.

### PR DESCRIPTION
**Pull request by cugone**
Closes #530
Closes #96 

This fixes the `std::min` and `std::max` functions being parsed as macros when `<windows.h>` is included and `#define NOMINMAX` is neither present nor included before all other headers.

Note: There is a use of `std::max` in the single-include header that does not appear anywhere else in the separated-out code. I could not find where the single-include header is generated to see where it's coming from.

### CODE REVIEW

**Comment by skypjack** [comment]
Please, don't update the single include file. It's generated automatically.
Instead, `runtime_view.hpp` uses `std::min`. It should be added to the PR.
Also, feel free to add yourself to the AUTHORS file if you like (lexical order).

**Comment by cugone** [comment]
> Please, don't update the single include file. It's generated automatically.

I've removed the changes to the single include file.

> Instead, `runtime_view.hpp` uses `std::min`. It should be added to the PR.

I did a search for "min" in `runtime_view.hpp` and the only occurrence is a single use of `std::min_element`. This is okay.

A search for `std::max` in literally every file reveals the only place `std::max` appears is in the single include header on line 8821. Where is this be generated from so it can be changed there? Just a thought, is the script used to generate the SIH using an out-dated file version? I ask because there are uses in `view.hpp` that have their functions declared `[[nodiscard]]` but the versions of those same functions in the SIH are not declared `[[nodiscard]]`.

**Comment by skypjack** [comment]
There is a script to generate the single include file. I update it regularly (well, more or less apparently :smile:).

**Comment by cugone** [comment]
Is the script part of the repo? If it is, where is it located?

**Comment by skypjack** [comment]
Yup, `script`. It's `amalgamate.py`, courtesy of I don't remember what project but there is a copyright note in the file.

**Pull request merged**
