### PR TITLE
Moved Friflo ECS to its own repo - before the ECS was a sub project o…

### PR DESCRIPTION
**Pull request by friflo**
Moved Friflo ECS to its own repo - before the ECS was a sub project of an ORM repository. Changed license to MIT.

### CODE REVIEW

**Comment by skypjack** [comment]
Can you make it point to the `wip` branch please? Thanks!

**Comment by friflo** [comment]
Switched branch to `wip`. Not sure if this fits to
> Can you make it point to the wip branch please"

If not. Please close PR and I will create a new one directly on `wip` branch.

**Comment by skypjack** [comment]
Yeah, there is something wrong for sure 🙂 I updated the file on my own though, not a problem.
Also updated the [wiki](https://github.com/skypjack/entt/wiki/Similar-projects) accordingly. 👍 
I'm closing the PR. No need to create a new one. Thanks for the heads-up.

**Comment by friflo** [comment]
Thx for your efforts!

I am still a git noob. Even using it for multiple years now :)

**Pull request closed without merging**
