### PR TITLE
Adding typename declaration on alias.

### PR DESCRIPTION
**Pull request by MichaelKuntzSkybox**

### CODE REVIEW

**Comment by MichaelKuntzSkybox** [comment]
So this a Visual Studio compile error. Just wanted to bring it to your attention.

**Comment by Kerndog73** [comment]
Is this a workaround for a bug in MSVC? `bool(uint32_t)` doesn’t contain any dependent names that need to be disambiguated with `typename`.

**Comment by skypjack** [comment]
Uhm... what you're proposing is wrong in C++ actually. The CI confirms it, all the tests just fail.  
What error do you have with MSVC? Also, what version of MSVC? The one from appveyor compiles it fine.

**Comment by MichaelKuntzSkybox** [comment]
Closing Pull Request, Was way off base and need to update MSVC, thankyou!

**Comment by skypjack** [comment]
You're welcome.

**Pull request closed without merging**
