### PR TITLE
Prototype of LSD radix sorting algorithm and an example of working wi…

### PR DESCRIPTION
**Pull request by MrMartinIden**

### CODE REVIEW

**Comment by skypjack** [comment]
I'm to merge this on `wip` and rework it a bit so as to make the algorithm _usable_ with `EnTT`. Just a note:
>sorts the elements in ascending order

Why do you explicitly mention this? Isn't it enough to pass reverse iterators to order everything in descending order?

**Comment by MrMartinIden** [comment]
> Why do you explicitly mention this? Isn't it enough to pass reverse iterators to order everything in descending order?
Yes, you are right. I wrote a note because of my little experience working with iterators, and in fact I copied the algorithm taken from the link.

**Comment by skypjack** [comment]
I've just realized that probably this cannot be used with a sparse set because of [this](https://github.com/skypjack/entt/blob/master/src/entt/entity/sparse_set.hpp#L528).  
Dumb question but have you ever tried to use this algorithm with the registry?

**Comment by MrMartinIden** [comment]
Yes, I had to copy EnTT functions related to sorting, and slightly modify the body of the copied functions so that they could accept a Getter function object. In principle, I can throw off the necessary functions, the problem is that there are so few changes that they are almost similar to the original functions.

**Pull request merged**
