### PR TITLE
Updated the README usage example to be proper.

### PR DESCRIPTION
**Pull request by M3TIOR**
:+1: Also now it's the same on Git and in the docs, so stubborn ass people like me don't have to dig through the source and test to validate what code is correct for the provided example use case.

Let's hope that teensy mistake didn't turn anyone away from this amazing ECS :worried:

### CODE REVIEW

**Comment by M3TIOR** [comment]
One of my teammates was having a hard time with it. I'm supprised nobody else has gotten to at least filing a GH issue for this yet seeing as this project is so widly used and popular. But then again a lot of people I know just copy and paste code unlike me lol.

**Comment by Innokentiy-Alaytsev** [comment]
AFAIK, [`emplace`](https://github.com/skypjack/entt/blob/master/src/entt/entity/registry.hpp#L634) is the new name of the function.

**Comment by skypjack** [comment]
Hi @M3TIOR first of all thank you for your kind words.
The README file as well as the wiki refer to `master`, so `emplace` is what you should use with it.
This is probably the mistake. You can find [here](https://skypjack.github.io/entt/) the documentation for the last stable release instead. As you can see, it still uses `assign` rather than `emplace`.
I'm sad you spent your time on this. I invite you to join the [gitter](https://gitter.im/skypjack/entt) for this kind of questions. It can save your time the next time. :wink:

**Comment by skypjack** [comment]
Btw now I'm curious to know what are you using `EnTT` for. :smile: 
Also, thanks for choosing it. Really appreciated. :heart:

**Comment by M3TIOR** [comment]
Thanks for responding so quick :slightly_smiling_face:. My friend started a development group for a game engine called Phoenix. That's what we're using EnTT in. If you'd like I could link the project so you can take a look :smile:.

**Comment by skypjack** [comment]
Sure. Feel free to drop a line here or in the gitter channel.
There is also a list of showcases in the wiki. If you reach something that you want to announce, you can also open a PR to add your project to that list. :wink:

**Pull request closed without merging**
