### PR TITLE
Fix entt::collector.where

### PR DESCRIPTION
**Pull request by suVrik**
Hello! I think `entt::collector` has a bug. The `where` function actually changes the first added matcher, not the last one. In the following example both of `where` calls update the `group` matcher instead of preceding `replace` matcher.

```
entt::observer(registry, entt::collector.group<ComponentA, ComponentB>()
                                        .replace<ComponentA>().where<ComponentA, ComponentB>()
                                        .replace<ComponentB>().where<ComponentA, ComponentB>())
```

Here's the fix.

### CODE REVIEW

**Comment by suVrik** [comment]
Btw, I personally would allow the `replace` matcher to be variadic as well.

**Comment by skypjack** [comment]
Do you think you can write a test for this to add to `observer.cpp`?

>Btw, I personally would allow the replace matcher to be variadic as well.

The reason for which it is not is that the list is always intended as if the types were `and`-ed. It wouldn't be misleading for `replace` because:
* Intuitively, I read `replace<A,B>` as: _replace `A` **or** `B`.
* To support `or`-ed types we need to store aside some information, that is something I want to avoid.

**Comment by suVrik** [comment]
Here's the test. I see the problem with variadic `replace` now.

**Comment by skypjack** [comment]
Thank you for the test. I'll also add you to the list of contributors unless you prefer not to be there. Let me know.

**Comment by suVrik** [comment]
That would be cool.

**Pull request merged**
