### PR TITLE
Prefix CMake Variables with ENTT.

### LINKED ISSUE #584: Add ENTT prefix to CMake Variables.
As discussed earlier on discord, we should prefix all CMake Variables with ENTT.
This is a standard convention and allows end users more flexibility.

### PR DESCRIPTION
**Pull request by GnikDroy**
Fixes #584 

Cache variables as well as normal variable names have been prefixed with ENTT. Relevant changes have been made to the README and workflow files.

### CODE REVIEW

**Comment by skypjack** [comment]
Should we add `-DENTT_BUILD_TESTING=ON` to the yml files for the CI too?

**Comment by skypjack** [comment]
Actually, probably also adding an option default for it would be good.
I can do it for my own by the way, not a problem. :+1:

**Comment by skypjack** [comment]
Sorry for being late, I've been a little busy lately.
Do you want to add yourself to the list of contributors before merging? See file `AUTHORS` (lexical order).

**Comment by GnikDroy** [comment]
No problem. No need to add my name to AUTHORS. Happy to contribute!

**Pull request merged**
