### PR TITLE
add implementation notes

### PR DESCRIPTION
**Pull request by dakom**
As discussed on gitter :) 

Not quite sure how this feeds into the wiki or if some other configuration is needed to propagate it somewhere...

### CODE REVIEW

**Comment by skypjack** [comment]
I had a first read of this. There is a bit of work to do to make it let's say _compliant_ with the current documentation.
I'll do it a bit at a time, no rush for this after all.

Do you mind if I copy-and-paste your doc in a gist to modify it when I've the time to do it and until it's done?
I can close the PR, update the whole thing and add credits to you directly in the document.

**Comment by dakom** [comment]
Feel free to do whatever you feel is best and helps make things clearer / more correct!

I appreciate the offer but no need to credit me - it's mostly re-wording and consolidating explanations from elsewhere (primarily your blog and discussions on gitter).

**Comment by dakom** [comment]
Btw I realized there's a few spelling mistakes, which I'll correct... but more importantly, the groups mechanism isn't explained enough. Will followup on Gitter when I can get to it and try to fill that out :)

**Comment by skypjack** [comment]
I waited too long, with the intention of integrating what was written and now things have changed a lot and will change again, due to custom storage support.
I close the PR because there is no point in merging it as it is. I'll take what I can from your proposal (citing the source as a contributor) and completely review the parts that no longer describe how `EnTT` works in fact.

Thanks for giving me a base to start from !! :)

**Comment by dakom** [comment]
oh, cool, no worries @skypjack ! For better or worse I haven't been able to get deeper into ECS stuff for a couple months or so... glad this helped in its way though :)

**Pull request closed without merging**
