### PR TITLE
Update AUTHORS

### PR DESCRIPTION
**Pull request by NixAJ**
As per request of skypjack, I'm creating this PR to include myself to the AUTHORS list.

### CODE REVIEW

**Comment by skypjack** [comment]
Hint: lexicographical order. :)

**Comment by NixAJ** [comment]
I wish I knew what that meant ;-;

**Comment by skypjack** [comment]
It means that your name goes after `m-waka` and not at the end of the file. :smile:

**Comment by NixAJ** [comment]
Fixed :D

**Pull request merged**
