### PR TITLE
Fight againts shared library boundaries

### PR DESCRIPTION
**Pull request by Innokentiy-Alaytsev**
A PR for wasting time while fighting against evil shared library boundaries.

### CODE REVIEW

**Comment by Innokentiy-Alaytsev** [comment]
@skypjack I have 2 questions:
* What could be a reason for one of the builds (Ubuntu, clang++) to be cancelled?
* May I ask you to look at the error GCC gives me? I don't understand how to fix it - as soon as I add `template<>` at where GCC wants to have it, it complains about too many template parameter lists.

On the bright side now it's 50% of passed pipelines 😃

**Comment by skypjack** [comment]
>What could be a reason for one of the builds (Ubuntu, clang++) to be cancelled?

Timeout **or** another build is failed. In this case all the others are stopped if possible.

>May I ask you to look at the error GCC gives me?

I hit it as well when experimenting and I've bad news for you... :smile:

**Comment by Innokentiy-Alaytsev** [comment]
>I hit it as well when experimenting and I've bad news for you... 

A rare situation where MSVC works better then something else 😈

**Comment by Innokentiy-Alaytsev** [comment]
I tried using `selectany` attribute as proposed by @dBagrat on Gitter and implemented [here](https://github.com/dBagrat/entt/commit/66934467dd06a406c30762be613f08fd31a2a2f5). But, of course, I've done it differently. 

The problem (?) with the @dBagrat version is that it uses a single identifier source for all families. It means that for some families identifiers will not start with `0`. Identifiers sequence of each family may have gaps due to identifiers being taken by another family in between current family types registration. It doesn't mean that this version should not be tested - it's just that I decided to test another approach that failed for obvious reasons.

Below is the updated `family.hpp` file contents. It has come stuff for debugging (see more on that below) and a change to how identifiers are generated. I didn't manage to make it work (probably even compile) properly for static class data-member so I used an internal namespace for holding the variables for me. I've added 2 variables: one for the identifier source and one for type identifier. Both are templated variables (yes, this is the root of all problems) so that the behaviour should be the same as before.
<details> 
  <summary>Updated `family.hpp`</summary>

```c++
#ifndef ENTT_CORE_FAMILY_HPP
#define ENTT_CORE_FAMILY_HPP


#include <type_traits>
#include "../config/config.h"

#include <iostream>
#include <typeinfo>
#include <string>
#define NOMINMAX
#include <Windows.h>


EXTERN_C IMAGE_DOS_HEADER __ImageBase;


inline std::string GetDllName () {
	CHAR   DllPath[MAX_PATH] = { 0 };
	GetModuleFileNameA ((HINSTANCE) &__ImageBase, DllPath, _countof (DllPath));

	return std::string{ DllPath };
}


namespace entt {


namespace family_internal {
	template<typename Family>
	ENTT_SELECT_ANY_ATTRIBUTE
	extern ENTT_MAYBE_ATOMIC(ENTT_ID_TYPE) identifier{};

	template<typename Family, typename... Type>
	ENTT_SELECT_ANY_ATTRIBUTE
	extern ENTT_ID_TYPE type = identifier<Family>++;
}

template<class...>
struct WhichType {};


/**
 * @brief Dynamic identifier generator.
 *
 * Utility class template that can be used to assign unique identifiers to types
 * at runtime. Use different specializations to create separate sets of
 * identifiers.
 */
template<typename... Tags>
class family {
public:
    /*! @brief Unsigned integer type. */
    using family_type = ENTT_ID_TYPE;

    /*! @brief Statically generated unique identifier for the given type. */
    template<typename... Type>
    // at the time I'm writing, clang crashes during compilation if auto is used instead of family_type
    inline static const family_type type =
		(std::cout
			<< GetDllName () << '\n'
			<< typeid(family<Tags...>).name() << '\t' 
			<< &family_internal::identifier<family<Tags...>> << '\t'
			<< typeid(WhichType<Type...>).name() << '\t'
			<< &family_internal::type<family<Tags...>, Type...> << '\t'
			<< '\n',
		family_internal::type<family<Tags...>, Type...>);
};


}


#endif // ENTT_CORE_FAMILY_HPP

```
</details>

Tests failed. So I decided to add some debugging output - using the debugger during static data initialisation was not fruitful. The code above contains code for getting the name of the DLL or executable for which the variables are initialised.

<details> 
  <summary>Debug output for initialisation</summary>

```
Family                                                               identifier addr     registered type                                             type id addr

W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib1.dll
class entt::family<struct entt::internal_dispatcher_event_family>    00007FFDFC5136C4    struct entt::WhichType<struct common_empty_event>           00007FFDFC5136C8
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib1.dll
class entt::family<struct entt::internal_dispatcher_event_family>    00007FFDFC5136C4    struct entt::WhichType<struct lib1_empty_event>             00007FFDFC5136D0
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib1.dll
class entt::family<struct entt::internal_dispatcher_event_family>    00007FFDFC5136C4    struct entt::WhichType<struct lib1_payload_event>           00007FFDFC5136D8
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib1.dll
class entt::family<struct entt::internal_dispatcher_event_family>    00007FFDFC5136C4    struct entt::WhichType<struct lib1_payload_hidden_event>    00007FFDFC5136E0
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib2.dll
class entt::family<struct entt::internal_dispatcher_event_family>    00007FFDF94EE6A4    struct entt::WhichType<struct common_payload_event>         00007FFDF94EE6A8
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib2.dll
class entt::family<struct entt::internal_dispatcher_event_family>    00007FFDF94EE6A4    struct entt::WhichType<struct common_empty_event>           00007FFDF94EE6B0
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib2.dll
class entt::family<struct entt::internal_dispatcher_event_family>    00007FFDF94EE6A4    struct entt::WhichType<struct lib2_empty_event>             00007FFDF94EE6B8
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib2.dll
class entt::family<struct entt::internal_dispatcher_event_family>    00007FFDF94EE6A4    struct entt::WhichType<struct lib2_payload_event>           00007FFDF94EE6C0
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher.exe
class entt::family<struct entt::internal_dispatcher_event_family>    00007FF705D392DC    struct entt::WhichType<struct common_payload_event>         00007FF705D392E0
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher.exe
class entt::family<struct entt::internal_dispatcher_event_family>    00007FF705D392DC    struct entt::WhichType<struct common_empty_event>           00007FF705D392E8
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher.exe
class entt::family<struct entt::internal_dispatcher_event_family>    00007FF705D392DC    struct entt::WhichType<struct lib1_payload_event>           00007FF705D392F0
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher.exe
class entt::family<struct entt::internal_dispatcher_event_family>    00007FF705D392DC    struct entt::WhichType<struct lib1_empty_event>             00007FF705D392F8
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher.exe
class entt::family<struct entt::internal_dispatcher_event_family>    00007FF705D392DC    struct entt::WhichType<struct lib2_payload_event>           00007FF705D39300
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher.exe
class entt::family<struct entt::internal_dispatcher_event_family>    00007FF705D392DC    struct entt::WhichType<struct lib2_empty_event>             00007FF705D39308
```
</details>

I've added debug output to the `dispatcher::assure()` function as well.

<details> 
  <summary>`dispatcher::assure()` update (the added lines)</summary>

```c++
std::cout
	<< GetDllName () << '\n'
	<< __func__ << '\n'
	<< typeid(event_family).name () << '\t'
	<< family_internal::identifier<event_family> << '\t'
	<< &family_internal::identifier<event_family> << '\t'
	<< typeid(Event).name () << '\t'
	<< family_internal::type<event_family, Event> << '\t'
	<< &family_internal::type<event_family, Event> << '\t'
	<< '\n';
```
</details>

<details> 
  <summary>Debug output during test case execution</summary>

```
Family                                                              identifier     identifier addr      type                            type id    type id arrd
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher.exe
assure
class entt::family<struct entt::internal_dispatcher_event_family>    6             00007FF705D392DC     struct common_payload_event     0          00007FF705D392E0
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher.exe
assure
class entt::family<struct entt::internal_dispatcher_event_family>    6             00007FF705D392DC     struct common_empty_event       1          00007FF705D392E8
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib2.dll
assure
class entt::family<struct entt::internal_dispatcher_event_family>    4             00007FFDF94EE6A4     struct common_payload_event     0          00007FFDF94EE6A8
W:\build\msvs-2017-Win64\entt\test\Debug\lib_dispatcher_lib2.dll
assure
class entt::family<struct entt::internal_dispatcher_event_family>    4             00007FFDF94EE6A4     struct common_empty_event       1          00007FFDF94EE6B0
```
</details>

The results are quite predictable: `selectany` doesn't work for template variables - each instantiation has a different address which leads to different identifiers for the same type in different libraries and on different sides of the border.

I've done some other tests with this setup but I don't have the debug output right now so stay tunned.

**Comment by Innokentiy-Alaytsev** [comment]
I've checked the results of other variants I've tried with `selectany` - they are more or less the same as the ones I posted before. At least I didn't find anything "new and interesting".

As for `dllexport`/`dllimport` approach, I've tried something completely different © and moved identifiers generation into namespaced functions. 

At first, I tried exporting identifier source and type identifier variables directly, but it didn't work out: with only identifier source (`family::identifier` analogue) as a variable, strange things get broken, and with identifier source being a function and type identifier being an exported variable cross-boundary case fails to work. It seems to have something to do with the order of initialisation or something along this line: the event type that is not exported from the library (internal/private for the library) gets the same identifier as one of the exported types from the other libraries.

With both identifier source and type identifier being encapsulated inside the functions, things seem to work in most cases. The only exception is MacOS which I don't have access to so I can't investigate what is happening there.

One important change that I've done is I made dispatcher family tag an actual type, even if an undefined one. I'll check it once again, but it seems that the types that are used as template arguments without being declared may have differently qualified names depending on where you mention them. I've stumbled upon it during experiments when I exported a template variable using simple `struct internal_dispatcher_event_family` template parameter and got an unresolved external symbol error. I couldn't understand what is going on until I re-read the error message carefully: unresolved symbol was something like `entt::family_internal::identifier<struct entt::family_internal::internal_dispatcher_event_family>`.

**Comment by skypjack** [comment]
You didn't push this changes, right?
Interesting the last part on unnamed types, it makes sense actually but I would never thought this before.

**Comment by Innokentiy-Alaytsev** [comment]
> You didn't push this changes, right?

Which changes? If you're talking about changes to `internal_dispatcher_event_family` then I've reverted them because everything works without it. But they are available as part of 55167ebd2969312a08d6117a5a78d2118ee28ae5 commit.

**Comment by Innokentiy-Alaytsev** [comment]
I've seen this problem before but I don't know when it happens and when it doesn't. As the tests run the same in both cases, it seems that this problem does not show up here. I'd use declared types as tags everywhere just to be safe but I'm paranoid.

**Comment by skypjack** [comment]
Nevermind. The mobile app makes me see only the commits since 2 weeks ago. I've just found the most recent ones from the web interface. :+1:

**Comment by Innokentiy-Alaytsev** [comment]
There's a GH mobile app?

**Comment by skypjack** [comment]
I'm using an unofficial app but they announced their own one last week. :+1:

**Comment by Innokentiy-Alaytsev** [comment]
@skypjack It may worth adding a CI pipeline for `clang-cl` toolset of Visual Studio 2017. It was the only toolchain that pointed out the lack of the `inline` specifier that was the reason of tests failing on MacOS.

**Comment by skypjack** [comment]
Fine for me but I've not idea how to setup it. There exists a cmake generator for that?

**Comment by pgruenbacher** [comment]
commenting to a) subscribe but also to declare I intend to test on production case when ready.

**Comment by skypjack** [comment]
@pgruenbacher you can follow the progresses on branches `lib` and `experimental`.

Long story short. `lib` contains a version that works across boundaries when you link the libraries. This isn't the _final_ version, mainly because I'll change something to put the `family` specializations out-of-classes and to allow custom generators. The latter are meant to make it work across boundaries with plugins or dynamically loaded libraries in general.

Any feedback is welcome also in this phase, as usual. :wink:

**Comment by skypjack** [comment]
Oh, @pgruenbacher I've still to update the documentation. I'll do it when the work is done. Therefore, feel free to make your questions here or in the gitter channel if you need more details. :+1:

**Comment by skypjack** [comment]
@Innokentiy-Alaytsev @pgruenbacher 
Branch `experimental` is ready for a merge on `master`.
I've updated the doc and added a lot of tests to avoid regressions in future. Everything works transparently.
If you like to test or review it, any feedback is appreciated. :wink:

**Pull request closed without merging**
