### PR TITLE
Properties list

### PR DESCRIPTION
**Pull request by Innokentiy-Alaytsev**
Implemented a function for adding a list of properties to meta-item.

### CODE REVIEW

**Comment by skypjack** [comment]
I was to do the same in the afternoon but I had to leave and didn't push.
My question is: why a custom data structure? I'd rather use the old, good approach of _whatever supports `get<N>`_. This works out of the box with an `std::pair` as well as an `std::tuple` and an `std::array` or even an `std::variant`.
Isn't it better than a custom data structure I should use only for this purpose?

**Comment by Innokentiy-Alaytsev** [comment]
I wanted those rvalue references. Not sure if it changes something. On the other hand `entt::a_prop` despite having an ugly name communicates the intention better than `std::pair`. I'll look into it.

**Comment by skypjack** [comment]
Forget about data members having type `T &&`. It looks like an XY-problem. What's your goal exactly?

**Comment by Innokentiy-Alaytsev** [comment]
Just want to pass the rvalues through, no other goal.

**Comment by Innokentiy-Alaytsev** [comment]
The other reason is that it's simpler) I could not get anything meaningful in 10 minutes. The other thing is that I was curious how will parameter packs work when they have different length.

**Comment by Innokentiy-Alaytsev** [comment]
Unfolding doesn't work for me with "anything with `std::get()`": https://godbolt.org/z/Dc3vhg

Using the recursive version is not fun because of compilation times.

**Comment by skypjack** [comment]
>Just want to pass the rvalues through, no other goal.

Ok but... why? This way I cannot pass lvalue references anymore.

>Unfolding doesn't work for me with "anything with `std::get()`

Sure, [it does](https://godbolt.org/z/IREvud).

**Comment by Innokentiy-Alaytsev** [comment]
> Ok but... why?

I guess it's just me being stupid) Right now I see no reasons for doing it this way.

> Sure, it does.

I thought about introducing an intermediate function the moment I turned my PC off after sending the previous comment.

There is a subtle point about "using anything compatible with `std::get()`" - sometimes it will do not what is intended:

 * An surrounding tuple is required if the user wants to add a key-only property that is of a type that is compatible with `std::get()` because otherwise, it may be unwrapped into a full property or into a property of a wrong type.

 * Trying to call `std::get()` on an `std::variant` instance that does not contain a value of the type with the provided index causes `std::bad_variant_access` to be thrown. Yes, it can be fixed during application testing but maybe unexpected for the users.

If you'd like I'll rework the PR to support "anything gettable" though. Of course, I shall remove those rvalue references in any case.

**Comment by skypjack** [comment]
>[...] a key-only property that is of a type that is compatible with std::get() [...]

Ok, I won't take in consideration this corner case because it's unlikely you'll use something like that for the properties and a solution exists anyway if you did it.

>Trying to call std::get() on an std::variant instance that does not contain a value of the type with the provided index [...]

As above, I cannot even imagine why one should use an `std::variant` to set up properties to be honest but still a workaround exists for such an extreme case.

You can't stop all possible users from doing all the silly things that come to mind. As long as there is an alternative solution for them, move on and work on something else. :wink:

**Comment by Innokentiy-Alaytsev** [comment]
What about a bargain: make the `properties()` function support anything "gettable" but have a simple convenience class `entt::a_prop` that is also gettable? Personally, I would really like not to have to write this class for every project or create a support library with this class alone. 

If you say "no" then I accept it and just make it work with anything "gettable" without any new DS's.

**Comment by skypjack** [comment]
Ahaha... we don't have to make a bargain. I'm just trying to understand why you need it. :wink: 
I mean, why you prefer to rely on a custom defined class to do that rather than on widely used tools that are designed for the same purpose?
At the end of the day, you're just re-inventing a pair with that class. It just happens that the two members are named `key` and `value` rather than `first` and `second`. Isn't it? What am I missing?

**Comment by Innokentiy-Alaytsev** [comment]
This small custom class better communicates the intent of creating a property. And the code is the same for both key-value- and key-only properties: `entt::a_prop{...}`. Having to use `std::tuple` for creating key-only properties, while all the other properties may be defined with `std::pair`, does not look beautiful to me. Of course, one may use `std::tuple` for everything but it only works if all properties are defined by the same person here and now. In legacy code with a team bigger than one person there is a chance of getting both `std::pair` and `std::tuple` (and maybe something else "gettable") in the same list. So it's not a problem of "it works" but of "how the code feels".

In fact, it's quite usual for me to overdo things because of this so some third opinion may be viable.

**Comment by skypjack** [comment]
Oh, wait, there is a misunderstanding. I'm not saying I want to use **only** `std::get`-table objects. Key only properties shouldn't require to use an `std::tuple`, I agree. These are the forms I'm thinking of:
```
.prop(key1, value1)
.prop(key2)
.prop(std::make_pair(key3, value3), std::make_pair(key4, value4), key5, std::make_pair(key6, value6), ...)
.prop<&annotation1, &annotation2, ...>() // function based properties
```
What do you think about?

**Comment by Innokentiy-Alaytsev** [comment]
I think this I can live with.

**Comment by Innokentiy-Alaytsev** [comment]
The `unpack` function has made this PR kinda lame and trivial)

**Comment by Innokentiy-Alaytsev** [comment]
A note regarding annotations. I just got a crazy idea: for enabling annotations (if they are used the way you've shown above) adding new properties passing a reference to the factory is required. With a reference for the factory, the annotations can do literally anything including adding new meta-members. That said, just sharing this crazy idea. Adding new meta-members from annotations will break the whole meta-state stack and all the following functions for adding properties will work with the wrong meta-item.

**Comment by skypjack** [comment]
Ahahah... yeah, I think it would be like giving a loaded gun to users, more than C++ already is. :smile: 

>The unpack function has made this PR kinda lame and trivial)

I commented the issue about annotations to propose a _review_ that fits with the current implementation.
We can safely close this PR probably, let me know. :+1:

**Pull request merged**
