### PR TITLE
benchmark to use entt::component

### PR DESCRIPTION
**Pull request by zaucy**
I ran into this while working on https://github.com/skypjack/entt/issues/287

### CODE REVIEW

**Comment by skypjack** [comment]
Oh, shame on me. I forgot to update the benchmarks.  
Thanks for pointing this out. I'll merge the PR as soon as I turn on the laptop.

Want you to edit also the AUTHORS file so as to add your name (in alphabetical order)? Otherwise I'll do it myself, it's not a problem.

**Comment by Kerndog73** [comment]
While you're at it, could you move Kerndog73 after Green-Sky? Mine seems to be the only name that's out of order!

**Comment by zaucy** [comment]
Added myself and moved @Kerndog73 ;P

**Comment by skypjack** [comment]
>Let me know if you want me to squash the AUTHORS update commit

Fine for me. I'm merging this on `wip` and then on `master` if everything works fine. :+1:

**Pull request merged**
