### PR TITLE
add single include of EnTT framework

### PR DESCRIPTION
**Pull request by Milerius**
Usefull for using in godbolt example:

https://godbolt.org/z/lqlKGS

### CODE REVIEW

**Comment by Milerius** [comment]
if you want to use it yourself.

`python3 scripts/amalgamate.py -c scripts/config.json -s .`

**Comment by skypjack** [comment]
This looks good. I'm guessing if we can automate it somehow using the CI or something similar.

**Comment by Milerius** [comment]
You can now also comparing assembly generated by `EnTT` and possibly inprove the code this way

**Comment by Milerius** [comment]
If you have python3 in the CI of course you can calling `python3 scripts/amalgamate.py -c scripts/config.json -s .`

**Comment by Milerius** [comment]
Usually you will do it only for release i think

**Comment by skypjack** [comment]
Yeah. The best thing would be if it triggered with a git hook on tags and created directly a PR or something on this line.

**Comment by Kerndog73** [comment]
Another thing that’s along the same lines is a precompiled header. I’ve never used them before so I’m not sure how much of a build-time reduction they provide. Maybe cmake could compile the single include header into a precompiled header. Maybe distribute precompiled headers for major compilers for convenience.

I don’t know. Just a thought.

**Comment by skypjack** [comment]
@Kerndog73 never used pch actually, I don't even know how to generate them, but I'm open to suggestion. :-)

**Comment by Kerndog73** [comment]
@skypjack It doesn’t look like cmake has built-in support for PCH. We’ll have to use [cotire](https://github.com/sakra/cotire). Maybe it’s too much effort!

Maybe I should stop beginning my sentences with “maybe”.

**Comment by Milerius** [comment]
In fact the single header is only for testing the framework out of the box on wandbor or godbolt for me

**Comment by skypjack** [comment]
Where did you get this `.py` file to create an amalgamation? It seems to me it makes just a raw copy of everything. Isn't there something a bit more elaborate to reduce the size of the final file?

**Comment by Milerius** [comment]
i stole it in nlohmann::json repository

**Pull request merged**
