### PR TITLE
adding git_shallow to cmake deps helps reducing building time

### PR DESCRIPTION
**Pull request by stefanofiorentino**
very useful in CI/CD pipelines

Signed-off-by: Stefano Fiorentino <stefano.fiore84@gmail.com>

### CODE REVIEW

**Comment by stefanofiorentino** [comment]
GIT_SHALLOW ON
Tell Git to clone with --depth 1. Use when GIT_TAG is not specified or when it names a branch in order to download only the tip of the branch without the rest of its history.

**Comment by skypjack** [comment]
if you like, add your name to the list of contributors (it's in alphabetical order).
Otherwise, let me know and I'll merge this as-is.

In both cases, thank you very much. :wink:

**Comment by stefanofiorentino** [comment]
already done 13 hours ago (I force-pushed), thanks.

**Comment by skypjack** [comment]
Oh, sorry, my fault. Missed it. Thanks. :+1:

**Pull request merged**
